### ISSUE TITLE
Move to Notion SDK 0.3.2.

### ISSUE THREAD

**Issue by HerIsDia** [cloudydeno/deno-notion_sdk#2]
Hi. 👋

Notion just release the v0.3.2: https://github.com/makenotion/notion-sdk-js/releases/tag/v0.3.2

I hope this will became really soon. ^^

**Comment by danopia** [comment]
Hey! My apologies but I didn't notice this issue - I have not been watching my own repo I guess!

I just pushed a v0.3.2 tag and will be following up quickly with the newer versions. Every version has merge conflicts so it's non-zero effort to take the updates.
