### ISSUE TITLE
time_zone in date property-value-object

### ISSUE THREAD

**Issue by danvoronov** [cloudydeno/deno-notion_sdk#4]
type error on this example

https://developers.notion.com/reference/property-value-object

{
  "Delivery Time": {
    "date": {
      "start": "2020-12-08T12:00:00Z",
      "time_zone": ""Europe/Kyiv""
    }
  }
}

**Comment by danvoronov** [comment]
Ok - according to src in not _string_ but _TimeZoneRequest_ type

but you have "Europe/Kiev" not "Europe/Kyiv"

**Comment by danvoronov** [comment]
in notion interface 
![image](https://user-images.githubusercontent.com/3093815/178749800-a1c0afc9-643e-4011-b820-e57f52c2ab7b.png)

**Comment by danopia** [comment]
Hey @danvoronov , thanks for reaching out.

> Ok - according to src in not string but TimeZoneRequest type
> but you have "Europe/Kiev" not "Europe/Kyiv"

This looks like an upstream issue as the API definitions come from Notion's official SDK and I see the same thing there:

https://github.com/makenotion/notion-sdk-js/blob/6c145804b395f4eb62a6a94ff39ffbd1eb1d2b5a/src/api-endpoints.ts#L4144

Perhaps file an issue on that repo? I resync semi-regularly to pick up the changes from the official upstream SDK.

In the meantime, I'd suggest casting e.g. `"Europe/Kyiv" as any` to workaround the issue.
